### ISSUE TITLE
An error was encountered while decompiling

### ISSUE THREAD

**Issue by supersaiyansubtlety** [QuiltMC/enigma#242]
Happened when I tried to name a param.

```
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
	at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1203)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:148)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at org.quiltmc.enigma.api.source.SourceIndex.resolveReferences(SourceIndex.java:142)
	at org.quiltmc.enigma.api.class_handle.ClassHandleProvider$Entry.lambda$continueIndexSource$17(ClassHandleProvider.java:272)
	at org.quiltmc.enigma.util.Result.andThen(Result.java:81)
	at org.quiltmc.enigma.api.class_handle.ClassHandleProvider$Entry.lambda$continueIndexSource$18(ClassHandleProvider.java:270)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
```

![java_hChhPZEm4V](https://github.com/user-attachments/assets/657ca14d-83d8-43c1-8bf7-4ac90c833b03)

**Comment by supersaiyansubtlety** [comment]
Worked on retry

**Comment by supersaiyansubtlety** [comment]
Another when setting the param of
`net/minecraft/unmapped/C_kouhnfig::m_cqycvonb`
(`net/minecraft/component/DataComponentMap::contains`)
```
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1521)
	at java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1575)
	at org.quiltmc.enigma.api.source.SourceRemapper.remap(SourceRemapper.java:20)
	at org.quiltmc.enigma.api.source.DecompiledClassSource.remapSource(DecompiledClassSource.java:48)
	at org.quiltmc.enigma.api.class_handle.ClassHandleProvider$Entry.lambda$continueMapSource$20(ClassHandleProvider.java:283)
	at org.quiltmc.enigma.util.Result.andThen(Result.java:81)
	at org.quiltmc.enigma.api.class_handle.ClassHandleProvider$Entry.lambda$continueMapSource$21(ClassHandleProvider.java:283)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
```
