### ISSUE TITLE
NullPointerException while loading jar

### ISSUE THREAD

**Issue by Tim203** [QuiltMC/enigma#67]
```
java.lang.NullPointerException: Cannot invoke "cuchaz.enigma.translation.representation.entry.ClassEntry.getName()" because "this.superClass" is null
	at cuchaz.enigma.translation.representation.entry.ClassDefEntry.isRecord(ClassDefEntry.java:83)
	at cuchaz.enigma.gui.util.GuiUtil.getClassIcon(GuiUtil.java:154)
	at cuchaz.enigma.gui.ClassSelector$1.getTreeCellRendererComponent(ClassSelector.java:105)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3220)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:728)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:111)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setModel(BasicTreeUI.java:505)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3900)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8716)
	at java.desktop/javax.swing.JTree.setModel(JTree.java:945)
	at cuchaz.enigma.gui.ClassSelector.setClasses(ClassSelector.java:201)
	at cuchaz.enigma.gui.Gui.setObfClasses(Gui.java:345)
	at cuchaz.enigma.gui.GuiController.refreshClasses(GuiController.java:390)
	at cuchaz.enigma.gui.Gui.onFinishOpenJar(Gui.java:301)
	at cuchaz.enigma.gui.GuiController.lambda$openJar$0(GuiController.java:115)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I looked at the source code for a bit and noticed that in the constructor of ClassDefEntry the `superClass` is annotated `Nullable`, but there doesn't seem to be a check for that in the methods using it.

**Comment by ix0rai** [comment]
should be fixed in `1.7.2`!
